name: Release

on:
  push:
    tags:
      - v*
jobs:
  build-on-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.xs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint files
        run: npm run lint

      - name: Test
        run: npm test

      - name: Bundle
        run: npm run bundle

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Build docker image
        run: |
          echo '${{ secrets.DOCKERHUB_PASSWORD }}' | \
          docker login \
            --username ${{ secrets.DOCKERHUB_USERNAME }} \
            --password-stdin
          export tag=${GITHUB_REF/refs\/tags\/v/}
          docker build . -t grafana/har-to-k6:$tag
          docker tag \
            grafana/har-to-k6:$tag \
            grafana/har-to-k6:latest
          docker push grafana/har-to-k6:$tag
          docker push grafana/har-to-k6:latest
